// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	addTodo: (content: string, dueDate: string | null) => typedError<Todo[], string>(__TAURI_INVOKE("add_todo", { content, dueDate })),
	deleteTodo: (id: string) => typedError<Todo[], string>(__TAURI_INVOKE("delete_todo", { id })),
	toggleTodo: (id: string) => typedError<Todo[], string>(__TAURI_INVOKE("toggle_todo", { id })),
	updateTodoContent: (id: string, content: string) => typedError<Todo[], string>(__TAURI_INVOKE("update_todo_content", { id, content })),
	loadTodos: () => typedError<Todo[], string>(__TAURI_INVOKE("load_todos")),
};

/* Types */
export type Todo = {
	id: string,
	content: string,
	done: boolean,
	due_date: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

